-- AlterTable
ALTER TABLE "deposits" ALTER COLUMN "value" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "transfers" ALTER COLUMN "value" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "withdrawals" ALTER COLUMN "value" SET DATA TYPE DOUBLE PRECISION;
